import Header from "@/component/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div>
        <h1 class="text-3xl font-bold underline">
    Hello world!
  </h1>
          {children}</div>
      </body>
    </html>
  );
}
